### ISSUE TITLE
BUG: Sparse master issue

### ISSUE THREAD

**Issue by kawochen** [pandas-dev/pandas#10627]
These other issues will be fixed by this
- [x] #667 other dtypes PR #13849
- [x] #10818 `from_coo` issues (same as #10560)
- [ ] #10079 empty construction
- [x] #10560 `__repr__` broken, PR #12779 
- [x] #10536 concat `SparseSeries`, PR #12844
- [x] #12174 concat `SparseDataFrame`? PR #12966
- [x] #4400 more testing of indexing (#12848)
- [x] #12794 more/better sparse docs PR https://github.com/pandas-dev/pandas/commit/b13ddd57f6f88f75d987dd84d208a2329f1d94bb
- [ ] #12855 return types
- [x] #13110 non float repr PR #13849
- [x] #13001 signatures PR #13849
- [x] #13144 repr of large arrays (#13163)
- [x] `SparseSeries` with `MultiIndex` indexing (#13163)
- [ ] `SparseDataFrame/Series` with `MultiIndex` indexing  (#15447)
- [ ] `SparseSeries` with non-unique index indexing 
- [ ] `SparseDataFrame` with non-unique index indexing 
- [ ] slicing / reindexing `SparseDataFrame` to return subclass (#13787)
- [ ] concat (#16874)

The fundamental issue is that slicing is broken in sparse.

```
In [11]: s = Series([1]+[np.nan]*5).to_sparse()

In [12]: s
Out[12]: 
0     1
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
dtype: float64
BlockIndex
Block locations: array([0], dtype=int32)
Block lengths: array([1], dtype=int32)

In [13]: s.iloc[0:3]
Out[13]: 
[1.0, nan, nan]
Fill: nan
BlockIndex
Block locations: array([0], dtype=int32)
Block lengths: array([1], dtype=int32)

In [14]: type(s.iloc[0:3])
Out[14]: pandas.sparse.array.SparseArray

In [15]: type(s)
Out[15]: pandas.sparse.series.SparseSeries
[14] should be a SparseSeries (not SparseArray which is the underlying object the SparseSeries holds). its not getting wrapped when sliced somewhere.
```

**Comment by jreback** [comment]
not sure why this is an issue 
can u show an example?

**Comment by kawochen** [comment]
For `Series` we get back the same type:
```
>>> type(Series([1, 2, 3]).iloc[1:2])
<class 'pandas.core.series.Series'>
>>> type(Series([1, 2, 3]).ix[1:2])
<class 'pandas.core.series.Series'>
```

```
>>> concat([Series([1, 2, 3]).iloc[0:1], Series([1, 2, 3]).iloc[2:3]])
0    1
2    3
dtype: int64
>>> concat([SparseSeries([1, 2, 3]).iloc[0:1], SparseSeries([1, 2, 3]).iloc[2:3]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kawoc/pandas-kawochen/pandas/tools/merge.py", line 755, in concat
    copy=copy)
  File "/home/kawoc/pandas-kawochen/pandas/tools/merge.py", line 806, in __init__
    raise TypeError("cannot concatenate a non-NDFrame object")
TypeError: cannot concatenate a non-NDFrame object
```

**Comment by jreback** [comment]
well are the same issue then

**Comment by kawochen** [comment]
hmm I suppose so, since that was the issue I was looking at.  I checked the history and the difference between `SparseSeries`'s fastpath  and `Series`'s fastpath seems deliberate (and tests do fail if I just make them the same), so I just wanted to point out `SparseSeries` hits paths that are not covered in tests, and we see things like `SparseSeries([1,2,3]).iloc[0:3]` and `SparseSeries([1,2,3]).iloc[:]` being different.

**Comment by kawochen** [comment]
#10079 is also the same issue (construction doesn't error, `.__repr__` does, but not for smaller frames)

**Comment by jreback** [comment]
@gfyoung hole host of issues w.r.t. sparse, note @sinhrks has recently fixed some of these

**Comment by gfyoung** [comment]
@jreback : Maybe I join the party here once I "finish" with `fromnumeric.py`.  Btw, I think `scipy.sparse` might be a useful resource in terms of getting ideas about functions, as they do a lot of their implementation in pure Python as well.

**Comment by jreback** [comment]
I don't think I made an issue for this, but we are open to taking ``sparse/array.py`` (and limited iinfrastructure), and making a ``pandas-sparse`` package to (that pandas would then depend). This would simplify the interface/API.

**Comment by gfyoung** [comment]
#12794 has been closed for some time now.

**Comment by gfyoung** [comment]
#667, #12794, #13001, and #13110 have all been closed for some time now.  Should all be checked off.
