### ISSUE TITLE
Period Resampling Master Issue

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#12871]
Various issue surrounding resampling with a `PeriodIndex`
- [x] #12884 Return PeriodIndex if possible
- [x] #12770 recursion error on existing freq (#12874)
- [x] #12774 count (#12874)
- [x] #12868 empty PeriodIndex (#12874)
- [x] #13212 empty dataframe (#13079)
- [x] #11983 with Panels?
- [ ] #7744 convention issues
- [x] #12883 recursion with 'W' freq when upsampling (#12874)
- [x] #13083 ohlc resampling
- [x] #13224 with NaT
- [ ] #14008 MultiIndex with TimeGrouper
- [x] #14213 Verify ``loffset`` works.
- [ ] #15146 Timestamp freq -> Period

**Comment by jreback** [comment]
cc @MaximilianR

**Comment by MaximilianR** [comment]
I can't edit the post, but I think all apart from these are solved: 

> #12884 Return PeriodIndex if possible
 #11983 with Panels?
 #7744 convention issues

**Comment by jreback** [comment]
@MaximilianR really?

we would need verifying tests only then.

**Comment by MaximilianR** [comment]
> we would need verifying tests only then

They should all have tests based on the PRs. (Your commits closed the issues, not me). Or lmk if I'm missing something

**Comment by jreback** [comment]
those all looks like one issues

**Comment by jreback** [comment]
oh sorry - you alll spat from those - I checked the boxes :)

**Comment by MaximilianR** [comment]
Adding to the list, `size` loses the Series name, after https://github.com/pydata/pandas/pull/13079:

```
In [4]: pd.Series([], name='test', index=pd.PeriodIndex([],freq='D')).resample('M').size()
Out[4]: Series([], Freq: M, dtype: int64)
```

**Comment by MaximilianR** [comment]
You can mark "#11983 with Panels?" off given Panel deprecation

**Comment by MaximilianR** [comment]
This is also fixed (although I think never had an issue): https://github.com/pandas-dev/pandas/issues/12871#issuecomment-220170356

**Comment by winklerand** [comment]
those are closed as well:
#12884 Return PeriodIndex if possible
 #13083 ohlc resampling
 #13224 with NaT

**Comment by mroeschke** [comment]
Looks like there's only 2 related period-resample issues left in the list (the Timestamp.freq one seems unrelated). I think it's just tractable to manage as individual issues. Closing
