### ISSUE TITLE
COMPAT: comparisons master issue

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#13129]
master issue for some comparisons
- [x] #13128, datetime with string on frame
- [x] #7830, datetimeindex vs other
- [x] #8932, timestamps with frame
- [x] #12601, tz comparisons
- [x] #9369, numeric and Series
- [ ] #11565, strings and numbers
- [x] #13200 Period and Series/Index

**Comment by Apeder** [comment]
Think I may have encountered this bug running Pandas on GAE Flexible: 
https://stackoverflow.com/questions/48509265/pandas-on-gae-flexible-wont-subset-dataframe/48512231#48512231

However, both dtypes were strings, so not sure exactly what's going on....

**Comment by mroeschke** [comment]
Looks like all the issues in the main post are fixed (and the last one just need a unit test). Closing.
