### ISSUE TITLE
TST: test_assert_index check index attributes 

### ISSUE THREAD

**Issue by sinhrks** [pandas-dev/pandas#13242]
- [x] `PeriodIndex.freq` (mandatory), #13250
- [x] `DatetimeIndex.tz` (mandatory)
- [x] `DatetimeIndex.freq` (add `check_freq` option with default False, because lots of tests compare op result (lost freq) and expected result created by `date_range` (has freq))
- [x] `TimedeltaIndex.freq` (same as above), #13250 
- [x] `CategoricalIndex` internals (`.codes` and `.categories`) (ref #13076, add `check_categorical` with default True), PR ##13249

**Comment by sinhrks** [comment]
I already have a branch which checks ``PeriodIndex.freq`` currently fails in empty resampling (fixed with #13079. 

https://github.com/sinhrks/pandas/tree/test_periodindex

**Comment by MaximilianR** [comment]
How about comparing the `attr` dictionaries (`._get_attribute_dict()`), rather than having the separate lookup above? 
That could also include `name`

**Comment by sinhrks** [comment]
There are mandatory and optional check. For example, our tests do something like `assert_frame_equal(df.a, df.b, check_names=False)`. Also, we have pickle tests to skip some attribute check like `Categorical.ordered`

**Comment by jreback** [comment]
@sinhrks I checked the ``freq`` boxes which I think closed by #13250

**Comment by sinhrks** [comment]
Thanks. Because #13250 only covers `PeriodIndex`, modified the boxes.

**Comment by jreback** [comment]
ok great!

**Comment by mroeschke** [comment]
Looks like all the above are implemented. Going to close this issue
