### ISSUE TITLE
DEPR: 0.21 deprecations master issue

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#14220]
Contemplated deprecations for 0.20.0
- [x] Deprecate `Panel`, #13563 (#15601) (0.20.0)
- [x] Deprecate `.ix`: https://github.com/pydata/pandas/issues/14218 (#15113) (0.20.0)
- [ ] Deprecate `.filter` & `.select` https://github.com/pydata/pandas/issues/12401 (#17633, 0.21.0)
- [ ] Deprecate `.between` https://github.com/pydata/pandas/issues/13027
- [x] Deprecate `.sortlevel` #14279 (#15099) (0.20.0)
- [ ] remove things in #6581 in 0.17.0
- [x] top-level namespace cleanup #13790 (0.20.0)
- [x] `TimeSeries` class (#15098) (0.20.0)

**Comment by wesm** [comment]
What do you think about pydata/pandas-design#26?

**Comment by jreback** [comment]
updated

**Comment by jorisvandenbossche** [comment]
@wesm @jreback All deprecated things are listed at https://github.com/pydata/pandas/issues/6581 (at least if we don't forget to add them). So normally, in a possible 0.20, we would remove all the things deprecated in 0.17, so that includes `pandas.ga`, TimeSeries, LongPanel, `pandas.rpy` etc. I think those are rather clear that they can be removed. I would keep this issue for new, possible controversial deprecations/tentative removals.

**Comment by jreback** [comment]
updated!

**Comment by jreback** [comment]
let's thing again about: https://github.com/pydata/pandas/issues/10734 (``.combine``)

**Comment by jorisvandenbossche** [comment]
Something we should discuss is whether we would like to remove things more aggressively (eg that were only deprecated in 0.18/0.19) for 1.0

**Comment by jreback** [comment]
long discussion about fixing the ``.rename/.reindex/.drop`` API to be consistent: https://github.com/pydata/pandas/issues/12392

**Comment by jorisvandenbossche** [comment]
> long discussion about fixing the .rename/.reindex/.drop API to be consistent

yes, I wanted to pick up that one for some time. I still think it can be done in a backwards compatible way, should look again at it.

**Comment by jorisvandenbossche** [comment]
See also https://github.com/pydata/pandas/issues/13790 for some top-level functions to deprecate

**Comment by TomAugspurger** [comment]
Moved filter & between to https://github.com/pandas-dev/pandas/issues/21894
