### ISSUE TITLE
pytest followup

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#15341]
Followup issues to https://github.com/pandas-dev/pandas/pull/13856
- [x] remove ``nose`` entirely (#15368)
- [x] fix ``yield`` base tests, see [here](https://ci.appveyor.com/project/jreback/pandas-465/build/1.0.3775/job/adkx3bghogwmekky). in ``computation`` and ``test_pickle.py``, replace with paramterization / fixtures. (#15406)
- [x] yield based tests in:
  - [x] frame/test_query_eval.py
  - [x] io/test_packers.py (#15427)
  - [x] io/test_pickle.py (#15416)
  - [x] test_internals.py (#15708)
  - [x] test_window.py (#15708)
- [x] use ``pytest-dist`` (#15369)
- [x] change generator based tests to  `addopts = --disable-pytest-warnings` from `setup.cfg`  (#15708)
- [ ] figure out getlocale failure on travis in ``pandas/tools/tests/test_util.py:TestLocaleUtils.test_set_locale``
- [ ] replace `@network` using pytest.mark (add other markers?)
- [ ] fix doc/source/contributing.rst reference to pd.test
- ~~[x] move ``conftest.py`` to top-level (#15731)~~
- [ ] use ``parametrize``https://github.com/pandas-dev/pandas/issues/15990
- [ ] use ``fixtures`` https://github.com/pandas-dev/pandas/issues/15990
- [x] list of skipped tests is failing (#15408)
- [x] ``nose.SkipTest`` -> ``pytest.skip()`` (or ``@pytest.mark.skip`` or ``skipif``) (#15368)

**Comment by bashtage** [comment]
One more candidate: Replace `SkipTest` with `pytest.skip()`

**Comment by jreback** [comment]
``pytest-sugar`` is interesting: https://travis-ci.org/jreback/pandas/jobs/200775014

looks good for single processor, not so great for mulit-cpu though.

**Comment by jreback** [comment]
https://github.com/box/flaky *might* be able to replace our home-made ``@tm.network`` decorators.

**Comment by jreback** [comment]
@TomAugspurger 

is the getlocale thing still an issue? 

everything else doesn't need an issue, so can close otherwise.

**Comment by TomAugspurger** [comment]
It's not a pytest specific thing, so yeah, we can close this one.
