### ISSUE TITLE
RLS: 1.0

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#17287]
Issue for tracking the 1.0 release (Early 2018)

See https://github.com/pandas-dev/pandas/wiki/Pandas-Sprint-(July,-2018) for goals / non goals of the release.

### Blockers

These are issues that should not be pushed to 2.x

- [x] [Numeric operations on all NaNs with bottleneck](https://github.com/pandas-dev/pandas/issues/9422)
- [x] [`.loc` not raising a `KeyError` when there's at least one missing label](https://github.com/pandas-dev/pandas/issues/15747) (PR https://github.com/pandas-dev/pandas/pull/17295); need to change this from a ``FutureWarning`` -> ``KeyError``
- [ ] `.rename / .relabel`: https://github.com/pandas-dev/pandas/issues/14829
- [x] [Harmonize drop / rename and axis](https://github.com/pandas-dev/pandas/issues/12392)
- [x] [Select / filter](https://github.com/pandas-dev/pandas/issues/12401)
- [x] Integer NA

### Miscellaneous FAQ

Q. Will python 2.7 be supported?
A. Probably not. Python 2.7 is being dropped at the end of 2018. 1.0 will probably be early 2019.

Q. Will new deprecations be introduced during 1.x?
A. Yes, but they won't be enforced until 2.0.

**Comment by jreback** [comment]
should prob move these to the roadmap / close / checkoff

**Comment by TomAugspurger** [comment]
I think this issue can be closed. https://github.com/pandas-dev/pandas/issues/14829 is the only one on this list not already solved.
