### ISSUE TITLE
TST: make _skip_if into pytest decorators

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#18190]
- [X] _skip_if_32bit (#18693)
- [X] _skip_if_no_mpl (#18427)
- [X] _skip_if_mpl_1_5 (#18682)
- [x] _skip_if_no_scipy (#18794)
- [x] _skip_if_no_lzma (#18820)
- [x] _skip_if_no_xarray (#18814)
- [X] _skip_if_windows_python_3 (#18693)
- [X] _skip_if_windows (#18693)
- [x] _skip_if_no_pathlib (#18765) 
- [x] _skip_if_no_localpath (#18765)
- [x] skip_if_no_ne (#18820)
- [x] _skip_if_has_locale (#18745) 
- [x] _skip_if_not_us_locale (#18745)
- [ ] _skip_if_no_mock
- [x] _skip_if_no_ipython (#18814)
- [ ] skip_if_no_package

we should move the ``_skip_if_*`` functions out of ``pandas.util.testing`` to another (private module)

then we can add [skipif decorators](http://pytest.readthedocs.io/en/reorganize-docs/new-docs/user/skipping.html)

and use like this

```
@skip_if_windows_py3
def test_.......():
```

rather than calling ``tm._skip_if_windows_py390`` in the body of the function (sometimes you also need to do that, so we leave the functions themselves as well).

this makes much more idiomatic and readable pytest code and removes the need to roll your own when using the decorator.

**Comment by WillAyd** [comment]
I could take a stab at this. What private module do you want the decorators to be in? Something like `_test_decorators.py` to enable `from pandas.util._test_decorators import *`?

**Comment by jreback** [comment]
i wouldn’t import * them but the name is ok

**Comment by WillAyd** [comment]
For the skipif decorators, we need to provide a function that evaluates to ``True`` to get it to skip whatever is being wrapped. A lot of the pandas-internal skip functions use pytest's ``importorskip``, which raises a ``Skipped`` when the required module cannot be imported.

I would propose here to catch a ``Skipped`` in the decorator function and return ``True`` if that occurs. Sample code is provided below to illustrate for mpl.

Before I go too far - do you agree with this direction? I'm somewhat hesitant to use it given the ``Skipped`` exception needs to be imported from ``_pytest``. However, the alternative would be to refactor the existing functions to not use importorskip, which has its own downsides. FWIW if we wanted to go with the try...except methodology I'd create a wrapper function internal to the _test_decorators module to handle that rather than coding that block for each decorator that we want to create

    import pytest
    from _pytest.outcomes import Skipped

    def _skip_if_no_mpl():
        try:
            mpl = pytest.importorskip("matplotlib")
            mpl.use("Agg", warn=False)
        except Skipped:
            return True
    
    skip_if_no_mpl = pytest.mark.skipif(_skip_if_no_mpl(), reason="No matplotlib")

**Comment by jreback** [comment]
I would refactor like your 2nd method, IOW have a safe importer that returns a boolean, then you could actually auto-create the functions & skip decorators.

**Comment by jreback** [comment]
certainly if you want a PR for a simple version would be great to see before you convert everything.

key is that *has* to be a separate module that is *only* imported when tests are run and not in pandas import (so deps are not imported until then)

**Comment by WillAyd** [comment]
Here's a complete listing of all of the methods that need to be converted. I may end up batching a few together as I go through:

- [ ] _skip_if_32bit
- [X] _skip_if_no_mpl (#18427)
- [ ] _skip_if_no_mpl_1_5
- [ ] _skip_if_no_scipy
- [ ] _skip_if_no_lzma
- [ ] _skip_if_no_xarray
- [ ] _skip_if_windows_python_3
- [ ] _skip_if_windows
- [ ] _skip_if_no_pathlib
- [ ] _skip_if_no_localpath
- [ ] skip_if_no_ne
- [ ] _skip_if_has_locale
- [ ] _skip_if_not_us_locale
- [ ] _skip_if_no_mock
- [ ] _skip_if_no_ipython
- [ ] skip_if_no_package

**Comment by WillAyd** [comment]
@jreback as far as the ``max_version`` argument goes in the current testing module's ``skip_if_no_package`` function I only since one usage in the following location:

https://github.com/pandas-dev/pandas/blob/7a0ee19e95e29042c3373a1d912d2db27108c828/pandas/tests/sparse/test_frame.py#L1234

I believe that was introduced by 56b5a30937e79335029b1727a80f109b7eb0840a and I looked through the related comments in #15668 but am not clear on why that particular test needs the v <= 0.19.0 criteria. Any insight as to if that is needed or not?

FWIW that test runs on my machine with SciPy 1.0, save the ``dok_matrix`` fixture which may have an unrelated issue.

**Comment by jreback** [comment]
@WillAyd I updated the top list, but I think I missed a couple.

**Comment by maxim-lian** [comment]
I'm looking at how we should skip tests in xarray. 

Why did you do this rather than pytest [`importorskip`](https://docs.pytest.org/en/latest/skipping.html#skipping-on-a-missing-import-dependency)?

**Comment by jreback** [comment]
importerskip is a hammer
we need fine grain skipping

**Comment by WillAyd** [comment]
Some other things to consider:

- The mark option is easy to apply to functions or classes interchangeably
- If using ``importorskip`` for a class (in the setup) you lose visibility to how many tests get skipped
- The mark option gives you metadata about your tests you miss out on with importorskip
