### ISSUE TITLE
STYLE: Additional flake8 checks

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#22122]
Currently we ignore some flake8 checks:

Checks that (currently) we're okay with skipping
-  E402,  # module level import not at top of file
-  E731,  # do not assign a lambda expression, use a def
-  W503   # line break before binary operator

Checks that should be run 
- [x]  E741,  # do not use variables named 'l', 'O', or 'I' #22795 (#23131)
- [x] C405,  # Unnecessary (list/tuple) literal - rewrite as a set literal.
- [x] C406   # Unnecessary (list/tuple) literal - rewrite as a dict literal.
- [x] C408,  # Unnecessary (dict/list/tuple) call - rewrite as a literal.
- [x] C409,  # Unnecessary (list/tuple) passed to tuple() - (remove the outer call to tuple()/rewrite as a tuple literal).
- [x] C410   # Unnecessary (list/tuple) passed to list() - (remove the outer call to list()/rewrite as a list literal).

Ideally, we should continue to lint our codebase with reasonable flake8 checks.

**Comment by jbrockmendel** [comment]
I’d be +1 on adding E741

**Comment by jbrockmendel** [comment]
I'm noticing in test_offsets `assert not MonthEnd() in _daterange_cache` which I would expect flake8 to complain should be `assert MonthEnd() not in _daterange_cache`.  Any idea why this isn't being chcked?

**Comment by jbrockmendel** [comment]
Recently saw flake8-eradicate, which looks for commented-out code.  It seems to produce a lot of false-positives, so we probably wouldn't want it in the CI, just a one-time run to do a dedicated remove-it-all sweep.

**Comment by jbrockmendel** [comment]
Not sure if this is specifically flake8, but it'd be nice to use a linter to prevent creep in the dependency structure.  Specifically, once a file has zero-runtime-imports, we could have a check to keep it that way.

**Comment by mroeschke** [comment]
Looks like our code checks are linting all the flake8 codes mentioned above. Going to close this issue out.
