### ISSUE TITLE
Add more pytest idiom to io.excel testing

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#26784]
master tracker for follow-ups to #26755 and related PRs

- [ ] use pytest.importorskip/not use the class structure https://github.com/pandas-dev/pandas/pull/26755#pullrequestreview-247416090 

- [ ]  location of fixtures https://github.com/pandas-dev/pandas/pull/26755#pullrequestreview-247404136

- [ ] imports and try/except https://github.com/pandas-dev/pandas/pull/26764#pullrequestreview-247587125 

- [ ] xlwt dependency/create a write_ext fixture https://github.com/pandas-dev/pandas/pull/26764#pullrequestreview-247589748

- [x] ~~use of safe_import in pytest.param https://github.com/pandas-dev/pandas/pull/26735#issuecomment-500156276~~ #27139

- [ ] parametrisation of write tests https://github.com/pandas-dev/pandas/pull/26740#pullrequestreview-247380174

- [ ] consider patch filename extension https://github.com/pandas-dev/pandas/pull/26740#pullrequestreview-247382411

- [ ] align the engine / ext usage in the Writer classes https://github.com/pandas-dev/pandas/pull/26662#pullrequestreview-246112315

- [ ] get rid of the None engine tests and just have a separate test that ensures how that gets bound to a particular engine https://github.com/pandas-dev/pandas/pull/26662#discussion_r291258182 (#28749)

- [x] ~~engine and ext injected into tests https://github.com/pandas-dev/pandas/pull/26662#discussion_r291260131~~ #28753

- [ ] add some doc-strings https://github.com/pandas-dev/pandas/pull/26579#pullrequestreview-245987920

- [ ] test_bad_engine_raises shouldn't parametrised https://github.com/pandas-dev/pandas/pull/26543#issuecomment-497126487 (#28749)

- [x] ~~Eliminate _WriterBase class~~ #28753

cc @WillAyd

**Comment by WillAyd** [comment]
Thanks for adding this!

**Comment by WillAyd** [comment]
*Some* of these I think should be pretty easy, particularly:

-  use of safe_import in pytest.param #26735 (comment)
- get rid of the None engine tests and just have a separate test that ensures how that gets bound to a particular engine #26662 (comment)
- add some doc-strings #26579 (review)
- test_bad_engine_raises shouldn't parametrised #26543 (comment)
- Eliminate _WriterBase class

So adding "good first issue" label to see if the community would like to pitch in on those

**Comment by awa5114** [comment]
Where is the `_WriterBase` class? I cannot find it...

**Comment by simonjayhawkins** [comment]
https://github.com/pandas-dev/pandas/blob/f8225bc68bd3326fa3c5191852ff776d1e78b6fd/pandas/tests/io/excel/test_writers.py#L224

**Comment by jbrockmendel** [comment]
one request that i think is related to this: in tests.io.excel.test_readers there are two fixtures called `cd_and_set_engine` that end up doing pytest.skip for some parameter pairs.  When I see the logs for this I think "oh there must be some missing dependency so we're not getting coverage on these many many skipped tests".  can we filter these cases at an earlier stage somehow?

**Comment by jbrockmendel** [comment]
#30456 affected the parametrization, not sure how this issue is affected.  is the checklist up-to-date?

**Comment by jbrockmendel** [comment]
@simonjayhawkins is this actionable/closeable?

**Comment by simonjayhawkins** [comment]
ok. closing for now. cleaning test files is a perpetual task.
