### ISSUE TITLE
Split large test modules

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#26807]
- [ ] pandas/tests/tseries/offsets/test_offsets.py #27085

- [ ] pandas/tests/test_resample.py #17806 (has now been split, some post split cleanup required)

- [ ] pandas/tests/io/test_pytables.py #18498

- [x] pandas/tests/test_window.py #19228

- [ ] pandas/tests/test_base.py #23877

- [x] pandas/tests/frame/test_indexing.py #25798

PRs welcome!

**Comment by moink** [comment]
I will take
pandas/tests/tseries/offsets/test_offsets.py

**Comment by moink** [comment]
Also @jreback requested pandas/tests/io/pytables/test_store.py in a comment on #38609

**Comment by moink** [comment]
pandas/tests/tseries/offsets/test_offsets.py is done

**Comment by moink** [comment]
The list in the issue text seems to be outdated. Here are the lengths and names of all test modules with more than 1000 lines:

5030   pandas/tests/io/pytables/test_store.py
3672   pandas/tests/test_strings.py
3316   pandas/tests/io/formats/test_format.py
3047   pandas/tests/io/test_sql.py
2522   pandas/tests/arithmetic/test_datetime64.py
2476   pandas/tests/tools/test_to_datetime.py
2414   pandas/tests/frame/test_constructors.py
2411   pandas/tests/test_algos.py
2389   pandas/tests/reshape/merge/test_merge.py
2367   pandas/tests/indexes/test_base.py
2280   pandas/tests/plotting/frame/test_frame.py
2208   pandas/tests/arithmetic/test_timedelta64.py
2203   pandas/tests/groupby/test_groupby.py
2188   pandas/tests/reshape/test_pivot.py
2141   pandas/tests/indexing/test_loc.py
2059   pandas/tests/computation/test_eval.py
1999   pandas/tests/io/test_stata.py
1933   pandas/tests/frame/test_stack_unstack.py
1908   pandas/tests/io/formats/test_style.py
1805   pandas/tests/resample/test_datetime_index.py
1756   pandas/tests/frame/indexing/test_indexing.py
1740   pandas/tests/io/json/test_pandas.py
1735   pandas/tests/frame/test_arithmetic.py
1700   pandas/tests/groupby/test_categorical.py
1666   pandas/tests/series/test_constructors.py
1638   pandas/tests/frame/methods/test_replace.py
1606   pandas/tests/io/parser/test_parse_dates.py
1578   pandas/tests/scalar/period/test_period.py
1576   pandas/tests/frame/apply/test_frame_apply.py
1536   pandas/tests/arithmetic/test_period.py
1517   pandas/tests/dtypes/test_inference.py
1516   pandas/tests/plotting/test_datetimelike.py
1494   pandas/tests/frame/test_reductions.py
1465   pandas/tests/tseries/offsets/test_yqm_offsets.py
1457   pandas/tests/io/formats/test_to_latex.py
1424   pandas/tests/reductions/test_reductions.py
1384   pandas/tests/io/excel/test_writers.py
1381   pandas/tests/arithmetic/test_numeric.py
1375   pandas/tests/reshape/merge/test_merge_asof.py
1359   pandas/tests/io/excel/test_readers.py
1340   pandas/tests/frame/methods/test_to_csv.py
1308   pandas/tests/arrays/sparse/test_array.py
1258   pandas/tests/io/test_html.py
1245   pandas/tests/frame/test_query_eval.py
1236   pandas/tests/arrays/test_datetimelike.py
1200   pandas/tests/io/json/test_ujson.py
1192   pandas/tests/groupby/transform/test_transform.py
1191   pandas/tests/indexes/datetimes/test_timezones.py
1179   pandas/tests/internals/test_internals.py
1177   pandas/tests/groupby/aggregate/test_aggregate.py
1149   pandas/tests/indexes/datetimes/test_constructors.py
1147   pandas/tests/indexing/test_coercion.py
1132   pandas/tests/window/test_rolling.py
1125   pandas/tests/indexing/test_indexing.py
1123   pandas/tests/groupby/test_function.py
1111   pandas/tests/groupby/test_apply.py
1099   pandas/tests/indexing/test_iloc.py
1085   pandas/tests/test_nanops.py
1071   pandas/tests/reshape/test_melt.py
1061   pandas/tests/io/test_parquet.py
1042   pandas/tests/dtypes/test_dtypes.py
1031   pandas/tests/scalar/timedelta/test_arithmetic.py
1016   pandas/tests/indexes/datetimes/test_date_range.py

**Comment by moink** [comment]
I will take
pandas/tests/io/pytables/test_store.py

**Comment by moink** [comment]
Done:
pandas/tests/io/pytables/test_store.py
I will take:
 pandas/tests/test_strings.py

**Comment by mroeschke** [comment]
Since this has one issue left, #27085, we can just track progress in that issue instead. Closing.
