### ISSUE TITLE
WEB: Blockers before moving the new website to production

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#28521]
List of issues that we must have implemented before we're happy to move the new website to production (so far the plan is to deploy the new website when we release pandas 1.0). xref #27870

- [x] New logo
- [ ] Improve home page #28168
- [ ] Fix styles #28519
- [x] Footer with the right content #28520
- [ ] Change the layout of the docs to match the one of the website #28580
- [ ] Deployment of the new website #28528

Anything else?

**Comment by jorisvandenbossche** [comment]
> Change the layout of the docs to match the one of the website (@jorisvandenbossche do we have an issue for this?)

I opened https://github.com/pandas-dev/pandas/issues/28580 for this.

**Comment by afeld** [comment]
I think it's since been deployed, and since issues for the outstanding tasks were split out, closing this one. Feel free to reopen if I'm misunderstanding!
