### ISSUE TITLE
ENH: Requested IO readers/writers

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#30407]
This is roundup issue to keep track of requested IO reader/writer formats.  If/when someone wants to implement a particular reader/writer, comment on the appropriate issue and we can re-open the discussion there.

- [ ] #7030 read fixed-width ASCII data using a data description file or dictionary file
- [ ] #9166 *SON RFC
- [ ] #9378 ROOT files
- [ ] #10517 ReadStat for binary format read/write
- [ ] #11752 avro
- [ ] #16846 shell command
- [ ] #22518 read_docx
- [ ] #23315 read_elastic/to_elastic using elasticsearch-py
- [ ] #27554 XML
- [ ] #29076 GraphQL

**Comment by jbrockmendel** [comment]
Added “IO format request” label to take the place of this tracker. Closing.
