### ISSUE TITLE
BUG: unexpected behavior of json_normalize meta arg

### ISSUE THREAD

**Issue by evan-anderson-ts** [pandas-dev/pandas#34465]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
test_input = [{
    "injection": {
        "time": "injection time"
    },
    "results": [
      {
        "time": "result time",
        "peaks": [{
           "name": "peak name A",
           "area": 1
        }, {
            "name": "peak name B",
            "area": 2
        }]
      },     
    ]
}]

df = pd.json_normalize(test_input, record_path=['results', "peaks"], meta=[["injection", "time"]])
print(df)
```
```
Output
          name  area injection.time
0  peak name A     1    result time
1  peak name B     2    result time
```

#### Problem description

I expected the string `"injection time"` to populate the `$.injection.time` column. Instead, the contents of `$.results.time` is populating this column. If I specify `meta=["injection"]`, then `{"time": "injection time"}` correctly populates the column.

#### Expected Output
```
          name  area injection.time
0  peak name A     1    injection time
1  peak name B     2    injection time
```

#### Output of ``pd.show_versions()``

<details>

/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
/usr/local/lib/python3.6/dist-packages/pandas_datareader/compat/__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.104+
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.4
numpy            : 1.18.4
pytz             : 2018.9
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 46.4.0
Cython           : 0.29.18
pytest           : 3.6.4
hypothesis       : None
sphinx           : 1.8.5
blosc            : None
feather          : 0.4.1
xlsxwriter       : None
lxml.etree       : 4.2.6
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.7.6.1 (dt dec pq3 ext lo64)
jinja2           : 2.11.2
IPython          : 5.5.0
pandas_datareader: 0.8.1
bs4              : 4.6.3
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.2.6
matplotlib       : 3.2.1
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 2.5.9
pandas_gbq       : 0.11.0
pyarrow          : 0.14.1
pytables         : None
pytest           : 3.6.4
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.4.1
sqlalchemy       : 1.3.17
tables           : 3.4.4
tabulate         : 0.8.7
xarray           : 0.15.1
xlrd             : 1.1.0
xlwt             : 1.3.0
xlsxwriter       : None
numba            : 0.48.0

</details>

**Comment by WillAyd** [comment]
Definitely looks buggy. The code for json_normalize is here if something you are interested in debugging:

https://github.com/pandas-dev/pandas/blob/1cad9e52ee1028db3bb4b9e86998104eb4d6b0ee/pandas/io/json/_normalize.py#L112

**Comment by evan-anderson-ts** [comment]
@WillAyd I had an opportunity to look at the json_normalize code. It seems like it currently only looks for metadata within the record path. Since both `$.injection.time` and `$.results.time` have the "time" key, we unintentionally grab `"results.time"` instead of `"injection.time"`. The logic to implement the behavior I expected is probably pretty tricky, not a simple debug. For now, it might be enough to document this behavior, and throw an error in this edge case I found (i.e. make sure that we don't accidentally grab the wrong metadata because there's a shared key between different branches of the json).

**Comment by olegbonar** [comment]
+1, faced this unexpected behavior today.

**Comment by tsteffek** [comment]
Encountered this today. Interesting to see that this still exists in version 1.4.1.

This stems by the way from the same problem as #40514 (one might call them duplicates): that `_recursive_extract` for some reason assumes it's fine to ignore the `meta`'s first level if it's already a level down in `record_path`.

**Comment by simonjayhawkins** [comment]
> Interesting to see that this still exists in version 1.4.1.

@tsteffek this is an open issue, so not yet fixed.

pandas is a community project. Anyone is welcome to submit a patch or contribute in other ways such as further investigation or suggesting fixes as you have here. Thanks.

**Comment by leonokubo** [comment]
The problem:
def _recursive_extract (Level + 1)

![image](https://github.com/pandas-dev/pandas/assets/8416376/3835e365-7bb3-4d15-b848-7aef43af79fc)

Solution:

from functools import reduce
import operator
for obj in _meta:
    seen_meta[".".join(obj)] = reduce(operator.getitem, obj, data[0])
