### ISSUE TITLE
TST/BUG: Unexpected warnings causing failures on master with fixed `assert_produces_warnings(None)` behavior

### ISSUE THREAD

**Issue by mzeitlin11** [pandas-dev/pandas#38630]
xref https://github.com/pandas-dev/pandas/pull/38626#issuecomment-749295555 

Making sure `assert_produces_warning(None)` raises if a warning is emitted gives the following failures in master due to unexpected warnings:
```
FAILED pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array[DataFrame-'UTC']
FAILED pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array[DataFrame-'US/Eastern']
FAILED pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array[DataFrame-'Asia/Tokyo']
FAILED pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array[DataFrame-'dateutil/US/Pacific']
FAILED pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array[DataFrame-'dateutil/Asia/Singapore']
FAILED pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array[DataFrame-'+01:15']
FAILED pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array[DataFrame-'-02:15']
FAILED pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array[DataFrame-'UTC+01:15']
FAILED pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array[DataFrame-'UTC-02:15']
FAILED pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array[DataFrame-tzutc()]
FAILED pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array[DataFrame-tzlocal()]
FAILED pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array[DataFrame-pytz.FixedOffset(300)]
FAILED pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array[DataFrame-<UTC>]
FAILED pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array[DataFrame-pytz.FixedOffset(-300)]
FAILED pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array[DataFrame-datetime.timezone.utc]
FAILED pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array[DataFrame-datetime.timezone(datetime.timedelta(seconds=3600))]
FAILED pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array[DataFrame-datetime.timezone(datetime.timedelta(days=-1, seconds=82800), 'foo')]
FAILED pandas/tests/frame/test_arithmetic.py::TestFrameArithmetic::test_binop_other[add-True-bool]
FAILED pandas/tests/frame/test_arithmetic.py::TestFrameArithmetic::test_binop_other[mul-True-bool]
FAILED pandas/tests/indexes/test_common.py::TestCommon::test_asi8_deprecation[int]
FAILED pandas/tests/indexes/test_common.py::TestCommon::test_asi8_deprecation[uint]
FAILED pandas/tests/indexes/test_common.py::TestCommon::test_asi8_deprecation[range]
FAILED pandas/tests/indexes/test_common.py::TestCommon::test_asi8_deprecation[repeats]
```

Tests which have been xfailed in #38626 are:

- [x] pandas/tests/arithmetic/test_timedelta64.py::TestTimedelta64ArithmeticUnsorted::test_tda_add_dt64_object_array
- [ ] pandas/tests/frame/test_arithmetic.py::TestFrameArithmetic::test_binop_other
- [ ] pandas/tests/indexes/test_common.py::TestCommon::test_asi8_deprecation
- [ ] pandas/tests/io/parser/test_common.py::test_chunks_have_consistent_numerical_type

**Comment by mzeitlin11** [comment]
Also seeing occasional `ResourceWarning` from `pandas/tests/io/parser/test_common.py::test_chunks_have_consistent_numerical_type[python]`

**Comment by simonjayhawkins** [comment]
@jbrockmendel did #39964 close this?

**Comment by jbrockmendel** [comment]
i dont think so

**Comment by simonjayhawkins** [comment]
OK not sure where the milestone came from. will remove.

**Comment by jbrockmendel** [comment]
@mroeschke might have been addressed by one of your recent PRs?

**Comment by mroeschke** [comment]
Yeah I think these no longer exist on main so closing
