### ISSUE TITLE
HackIllinois 2021 Open Source Fellowship mentoring

### ISSUE THREAD

**Issue by afeld** [pandas-dev/pandas#39349]
Just got this email:

> My name is Rishin and I am one of the Directors of HackIllinois- the largest hackathon in the Midwestern United States with a focus on Open Source initiatives. Today, I am reaching out to invite you or another member of the Pandas team to be a mentor for a new Open Source Fellowship program we're organizing from February 15th-March 5th, 2021!
> 
> HackIllinois has long been an Open Source hackathon with the mission to introduce students to Open Source projects and the greater Open Source community and has attracted 1500+ applicants from around the world every year. This year, however, we're reevaluating the efficacy of the hackathon format in furthering this mission. Instead, we're hoping our new long-term program with asynchronous mentorship and weekly check-ins will increase retention amongst students, bringing new members to the Open Source community!
> 
> We’d love to have somebody from the Pandas team share their experiences with the project and more this year from February 15th-March 5th, 2021 through our new program. As a mentor, you would guide a group of a few passionate and dedicated students through the process of contributing to an open-source project. This would include anything from navigating the codebase to making contributions of their own. We would be grateful to have you join us in bringing new members to the Open Source community!
> 
> Please let me know if you’re interested in this event or know anybody else on the team who may be! If you have any questions, I’d be happy to hop on a quick call to discuss your potential involvement!

I'm going to offer to mentor contributions to the docs; reach out to ~~mentor@hackillinois.org~~ contact@hackillinois.org if interested in participating.

~~Will plan to close this issue after a few days, since there isn't an action item for the project really.~~

## TODOs

- [x] Express interest
- [x] Meet with organizers
- [x] Complete mentor registration
- [x] Collect list of potential projects
   - Specify relative technical difficulty, time commitment, and depth of pandas knowledge required. Maybe other things?

**Comment by afeld** [comment]
Just chatted with the organizers. Notes from the call:

- Goal of everyone submitting at least one pull request in the three weeks
- Participants and mentors will get put into Slack channels to communicate
- Matching
  - "Touring period" on Friday 2/12: every student "visits" every project
    - Can set hours for live Q&A over Zoom, or just provide info for them to learn about the project and potential tasks
  - Students rank top three projects
  - Mentors can interview students on 2/13-14 if they like
  - Students assigned on 2/15, which is when it officially starts
- Students expected to do 2-3 hours per week
- Mentors should expect to do a sync with students once per week
- Anywhere from 1-10 students per mentor; up to the mentor
- Will be appealing that documentation contributions are beginner-friendly
- Going to try to pair students with mentors in similar time zones
  - Some mentors are in other countries
- Mentors can give a workshop if they like; any time, any format
  - I have a [pandas crash course](https://colab.research.google.com/github/afeld/python-public-policy/blob/main/pandas_crash_course.ipynb) ready to go
  - Organizers will send some options
- Students will do final presentations reflecting on what they learned
  - Mentors optional
  - Will take place on [3/4 after 5pm CT](https://everytimezone.com/?t=603ed180,b04), exact time to be determined
- Students most interested in projects they have experience in

Adding some TODOs up top.

**Comment by afeld** [comment]
[Official mentor information](https://docs.google.com/document/d/1MTXOfM4yugPI5LCg1InOMA-aLllKnC0qOFUDmIcMXL4/edit)

**Comment by afeld** [comment]
Running list of issues selected from [`Docs` + `good first issue`](https://github.com/pandas-dev/pandas/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+label%3ADocs+):

- Writing
   - https://github.com/pandas-dev/pandas/issues/38990
   - https://github.com/pandas-dev/pandas/issues/26195
- Coding
   - https://github.com/pandas-dev/pandas/issues/38996
   - https://github.com/pandas-dev/pandas/issues/25106
   - https://github.com/pandas-dev/pandas/issues/21354

**Comment by afeld** [comment]
The Fellowship has ended. Nice work on your first open source and pandas contributions (respectively) @madhuv2002 (https://github.com/pandas-dev/pandas/issues/40215) and @Bhard27 (https://github.com/pandas-dev/pandas/pull/39965)!
