### ISSUE TITLE
ENH: consistency of input args for boundaries

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#40245]
There are some methods where boundary inputs are required.

This issue proposes standardising to the keyword arg: `inclusive` and using values `{"both", "neither", "left", "right"}`.

- [x] Styler.highlight_between():  `'inclusive' in {"both", "neither", "left", "right"}` 
- [x] Series.between() (#40628): `'inclusive' in {"both", "neither", "left", "right"}` 
- [x] pd.date_range() https://github.com/pandas-dev/pandas/pull/43504
- [x] DataFrame.between_time() https://github.com/pandas-dev/pandas/pull/43248
- [ ] pd.Interval https://github.com/pandas-dev/pandas/pull/46522
- [ ] pd.interval_range https://github.com/pandas-dev/pandas/pull/46355
- [ ] pd.IntervalIndex https://github.com/pandas-dev/pandas/pull/46522
- [ ] pd.cut
- [ ] Series.resample
- [ ] DataFrame.rolling(closed)

More methods yet to be identified.

**Comment by hewittk** [comment]
take

**Comment by hewittk** [comment]
> Does anyone have the link for the Styler.highlight_between proposed method?

Also, are there any other methods or functions that you have in mind? 
@attack68

**Comment by attack68** [comment]
https://github.com/pandas-dev/pandas/pull/39821#discussion_r590789147

so you can see part of the discussion there, that PR is not yet approved, possibly this is a small part of the reason. There is mention of some other functions (non-exhaustive) list that have boundary treatment arguments. Do you know how well numpy handles this, and what style they adopt?

**Comment by attack68** [comment]
one possible solution if it check outs might be to extend `Series.between` to adopt {both, neither, left, right}, whilst maintaining True is 'both' and False is 'neither' for backwards compatibility.

I also dont think anyone would object to a logical enhancement of the input argument to `Series.between`.

^just a quick suggestion.

**Comment by attack68** [comment]
Reopening this issue after observing more methods where standardising might be appropriate. (see OP)

**Comment by YasmeenAlsaedy** [comment]
I would like to take `pd.date_range()` but can you please explain more what should change in this method @attack68

**Comment by suyashgupta01** [comment]
I want to work on `Dataframe.between_time()`, is there something else I should know before getting started? @attack68

**Comment by suyashgupta01** [comment]
take

**Comment by suyashgupta01** [comment]
Hi @attack68, for `Dataframe.between_time()`, the boundary related arguments are `bool include_start` and `bool include_end`. I'll go ahead and let them stay there for backwards compatibility, and add a new `inclusive` argument. Please let me know if I should adopt another course of action.

**Comment by suyashgupta01** [comment]
I've made & tested all the aforementioned changes locally, everything seems to be working fine. 

Now, I'm aware that I need to write code for tests in the repository before I make a pull request, can anyone please guide me regarding the same.

**Comment by zyc09** [comment]
take

**Comment by zyc09** [comment]
working on pd.date_range()

**Comment by suyashgupta01** [comment]
As mentioned [here](https://github.com/pandas-dev/pandas/pull/43248#discussion_r701003907) by @attack68 , I'll soon be making a follow up PR for this. :)

**Comment by carbonleakage** [comment]
Hey @attack68, looks like no one is working on pd.cut and Series.resample yet? I notice that there are few open questions related to pd.cut as noted in some of the other issues (for example #23164 and #33912), I will work on it once some of these relevant issues are closed. So I am thinking of working on Series.resample first, any comments?

**Comment by carbonleakage** [comment]
take
