### ISSUE TITLE
DEPR: `DataFrame.to_html` in favour of `Styler.to_html`

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#41693]
The tracker of items needed to do before deprecating `DataFrame.to_latex()`.

- [x] acceptance of the `jinja2` requirement for HTML output, since `Styler` requires `jinja2`: this is blocker.
- [x] make Styler functional for all DataFrames (i.e. including non-unique columns, indexes) (#41269).
- [ ] enhance with ability to style indexes/column headers with styles (e.g bold rows).
- [ ] enhance `.hide_columns` with `.show_columns` alternative (optional)
- [ ] add the sparsify kwargs
- [ ] decide whether to add or drop max_rows / max_cols / min_rows
- [ ] enhance `.hide_columns` and `.hide_index` to have dual function to hide the entire array, or specific items (#41266)
- [x] make styler reactive to separate sparse columns and index separately  (#41512)
- [x] acceptance of removal of specific kwargs and all formatting keyword args (see below).

### Removed Keyword Args

`col_space`: **removed** since `Styler.to_html()` should be controlled by the CSS as defined by other methods: `df.style.set_table_styles([{'selector': 'th', 'props': 'min-width: 100px;'}]).to_html()`
`index_names`: **removed** and assumes index names will be cleared or set prior to rendering.
`justify`: **removed** since this is a styling arg which should be dealt with by other methods.
`columns`: **replaced** by `df.style.hide_columns(list).to_html()`, or otherwise subselecting a DataFrame before rendering.
`header`: **replaced** by `df.style.hide_columns().to_html()`, or otherwise column names must be set prior to rendering.
`index`: **replaced** by `df.style.hide_index().to_html()`
`sparsify`: **replaced** by alternative kwargs `sparse_index` and `sparse_columns`
`multicolumn`, `multicolumn_format`, `multirow`: **replaced** by alternative kwargs `multirow_align` `multicol_align`
`na_rep`, `formatters` `float_format` `decimal` `escape`: **replaced** by the superior `df.style.format(...).to_html()`
`show_dimension`: **removed** since not relevant for `to_html`
`border`: **removed** since is deprecate HTML and should be controlled with CSS.
`render_links`: **removed** is a formatting arg and should be dealt with by `format()`.

**Comment by Lokeshrathi** [comment]
This would come in so handy to me for reporting and sending automated mailing purposes, any heads up by when it can be released?

**Comment by attack68** [comment]
@Lokeshrathi don't understand what you mean. This issue is about a deprecation of one function currently available by a function also already available on master?

**Comment by rhshadrach** [comment]
@attack68 - from #44451 it appears that you and @jorisvandenbossche are in favor of keeping `DataFrame.to_html` as a wrapper around `Styler.to_html`. I'm +1 here as well. I've retitled this issue to reflect that and removed the deprecation tag, but please adjust if this is not correct.

**Comment by jbrockmendel** [comment]
Is this a duplicate of #11700?  If so let’s close that as this is more fleshed out.

**Comment by attack68** [comment]
Yes probably. All the key elements seem to be in place to achieve this. And the implementation should probably mirror #41649 which transitioned `to_latex` successfully. It has been working well for years now without many reported issues. 

I ran into a few hurdles there regarding deprecation warnings and our of cycle changes. In honesty `to_latex` had less visibility so I managed to push it through and fix things later.

The format of string output is also not exactly the same across the different implementations (although this is irrelevant to rendered output) so gave an additional reason to pushback.
