### ISSUE TITLE
API: Breaking Changes in 3.0 (without deprecations)

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#44823]
Discussed on today's call, this issue to discuss potential changes we may want to make in 3.0 that are too big or cumbersome to deprecate.

- [ ] offsets.Day DST behavior #44364 
- [ ] <s>#29962 </s> Not going to make it into 3.0
- [x] #34916
- [x] `Index.__eq__(Series)` return NotImplemented #36759
- [x] concat with empty or all-NA entries #40893, #39122
- [x] #52676
- [x] Have MultiIndex attributes return tuple instead of FrozenList https://github.com/pandas-dev/pandas/issues/53531
- [x] https://github.com/pandas-dev/pandas/issues/54154

**Comment by mroeschke** [comment]
Not completely, https://github.com/pandas-dev/pandas/pull/50593 did not add axis=None for sum, prod, var, std, sem

**Comment by mroeschke** [comment]
@jbrockmendel should we push this as breaking changes for 3.0 without deprecations or should we just start a new issue when we're toward the end of the 2.0 cycle?

**Comment by jbrockmendel** [comment]
im fine re-purposing this

**Comment by jbrockmendel** [comment]
think the axis=None one is still viable to get for 2.0?

**Comment by mroeschke** [comment]
Could be possible. I think the ones not addressed take slightly different code paths so not sure if supporting that is straightforward.

IMO it should be not blocking for 2.0
