### ISSUE TITLE
Meta issue: CI refactoring

### ISSUE THREAD

**Issue by jonashaag** [pandas-dev/pandas#46643]
As suggested here https://github.com/pandas-dev/pandas/pull/46538#issuecomment-1088136015 I'm going to maintain this meta issue for my CI PRs. I will update it with any PRs I'm opening, and whenever the following "PR plan" becomes more concrete.

- [x] Drop Azure and move to GHA
  - https://github.com/pandas-dev/pandas/pull/46611
- [x] Cache entire Conda envs to save 5–10 minutes per job
- [ ] Add Ccache to cache C compilation to save 5–10 minutes per job
  - https://github.com/pandas-dev/pandas/pull/47360
- [ ] Add a Windows 32 bit build
- [ ] Drop the Ubuntu 32 bit build
- [ ] Refactoring
  - https://github.com/pandas-dev/pandas/pull/46540
  - https://github.com/pandas-dev/pandas/pull/46541
  - https://github.com/pandas-dev/pandas/pull/46542
  - https://github.com/pandas-dev/pandas/pull/46543
  - https://github.com/pandas-dev/pandas/pull/46538
  - https://github.com/pandas-dev/pandas/pull/46541
  - https://github.com/pandas-dev/pandas/pull/46611
  - https://github.com/pandas-dev/pandas/pull/47293
  - https://github.com/pandas-dev/pandas/pull/47292

**Comment by jonashaag** [comment]
cc @datapythonista @jreback @mroeschke @lithomas1

**Comment by mroeschke** [comment]
Looks like most of these are done?

**Comment by jonashaag** [comment]
Yep! I want to add Ccache and then have another look at what’s worth optimizing, in particular in terms of latency reduction for devs
