### ISSUE TITLE
API: Deprecate Index.is_(boolean|categorical|integer|floating|numeric|object|interval)

### ISSUE THREAD

**Issue by topper-123** [pandas-dev/pandas#50042]
### Feature Type

- [ ] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [X] Removing existing functionality in pandas

### Problem Description

I propose deprecating the mentioned methods on `Index`.

I suggest dtype checking should be the same for indexes, series and arrays, so e.g. if users want to check the dtype of an index they should use the functions in `pandas.api.types`, e.g. for numeric dtype checks, do `pd.api.types.is_numeric_dtype(idx)`.

### Feature Description

Deprecate the mentioned methods and make users use the functions they'd use for series, i.e. the dtype checking functions in `pandas.api.types`.

### Alternative Solutions

The alternative is not deprecating the methods...

### Methods to deprecate:

- [x] is_boolean (PR: #50176)
- [x] is_integer (PR: #50178)
- [x] is_floating (PR: #50235)
- [x] is_numeric (PR: #50769)
- [x] is_object (PR: #50227)
- [x] is_categorical (PR: #50225)
- [x] is_interval (PR: #50196)

**Comment by jbrockmendel** [comment]
+1

**Comment by topper-123** [comment]
take

**Comment by topper-123** [comment]
I've started working on this, one method at a time.

This issue is quite beginner friendly, so If someone wants to join in, they're welcome and I can guide you through it.

**Comment by ShisuiUzumaki** [comment]
@topper-123 I am interested in this issue. Could you guide m on how to take it?

**Comment by topper-123** [comment]
I don’t know if the above is sufficient information, but if you’ve got any questions, just get back to me.

**Comment by ShisuiUzumaki** [comment]
Okay, thanks. I will start working on it and will connect with you if need any guidance.

**Comment by yuuun** [comment]
Can I have a try?

**Comment by bang128** [comment]
I am also looking for a good first issue to work on. Is there anything I can help for this issue?

**Comment by topper-123** [comment]
@yuuun , you could take is_floating and @bang128 you could take is_object.

is_numeric may be a bit more complex (it’s treatment of complex numbers and booleans may differ from types.api.is_numeric), but if someone wants to take it, just ping me and I can guide you.

**Comment by yuuun** [comment]
take

**Comment by topper-123** [comment]
great, I see you've started the PRs. Ping me when you're ready for feedback.

**Comment by jbrockmendel** [comment]
@topper-123 one that will be more difficult (i.e. NOT a good first issue) but that i would find very nice is getting rid of holds_integer.

**Comment by topper-123** [comment]
@jbrockmendel , yeah I can take that.

**Comment by topper-123** [comment]
Anyone up for taking on `is_object` & `is_numeric`?

`is_numeric` is a bit more complex than the other as I mention above, but is still doable and is a good learning experience.

**Comment by ABCPAN-rank** [comment]
@topper-123 I'm interested in this issue. Can i try to deprecate is_object ?

**Comment by topper-123** [comment]
Yes! Ping me when the PR is ready for review.

**Comment by topper-123** [comment]
@ABCPAN-rank, we had a PR for `is_object already` (#50227), that just wasn't listed in the original  comment at the time when I answered you. Are you up for trying `is_numeric` (it's a bit more difficult)?

**Comment by ABCPAN-rank** [comment]
@topper-123  yes，i can try it. When index include complex or bool , __is_numeric__ will output flase and __is_numeric_dtype__ will output True . Dose this mean i should change __is_numeric_dtype__?

**Comment by topper-123** [comment]
`is_numeric_dtype` should not be changed. Just use `is_numeric_dtype` as-is, and add use of `is_bool_dtype`, `is_complex_dtype` as needed.

**Comment by ABCPAN-rank** [comment]
Do you mean i can use ```is_numeric_dtype(idx) and not is_bool_dtype(idx) and not is_complex_dtype(idx)``` instead of ```idx.is_numeric()```   ?

**Comment by topper-123** [comment]
Yes, where it's needed. There may also be places where it's ok to pass complex numbers and booleans.

**Comment by topper-123** [comment]
Closing as completed.
