### ISSUE TITLE
Consistency with groupby as_index

### ISSUE THREAD

**Issue by hayd** [pandas-dev/pandas#5755]
Checklist:
- [x] head and tail act like filter
- [x] nth act like filter
- [x] nth on Series should dropna? (discuss?)
- [ ] something subtle with some functions in agg/apply (again)
- [ ] go through other methods to see if as_index acts correctly
- [ ] cythonized vs with apply #7002
- [ ] get_group with `as_index=False`, #5764
- [ ] returned group for a DataFrame.groupby.cumsum(), #5614 / https://github.com/jreback/pandas/commit/371a7bf6ce330bcfe24d9b39118d5f4dc1292cbf / just need to test for transformers (that they ignore `as_index`)

I've had this half-written for a while, but I wasn't sure actually explain it. I'm still not sure, but here goes.

Would be intersting to discuss what peoples views on the correctness of these was.

I think there's scope for cleaning up some possible inconsistencies (unfortunately this would mean breaking the API):

```
In [2]: df = pd.DataFrame([[1, 2], [1, 4], [5, 6]], columns=['A', 'B'])

In [3]: g = df.groupby('A', )

In [4]: g1 = df.groupby('A', as_index=False)

In [5]: g.head(1)   # I did a dirty hack to get the index like this!
Out[5]: 
     A  B
A        
1 0  1  2
5 2  5  6

In [6]: g1.head(1)
Out[6]: 
   A  B
0  1  2
2  5  6

In [7]: g.nth(0)
Out[7]: 
   B
A   
1  2
5  6

In [8]: g1.nth(0)  # the index doesn't match the original
Out[8]: 
   A  B
0  1  2
1  5  6

In [9]: g.filter(lambda x: x.B>0)
Out[9]: 
   A  B
0  1  2
1  1  4
2  5  6

In [10]: g1.filter(lambda x: x.B>0)
Out[10]: 
   A  B
0  1  2
1  1  4
2  5  6

In [13]: g.apply(lambda x: x.sum()) 
Out[13]: 
   A  B
A      
1  2  6
5  5  6

In [14]: g1.apply(lambda x: x.sum())  # but as_index=False
Out[14]: 
   A  B
A      
1  2  6
5  5  6

In [15]: g.apply(lambda x: x)  # no index ?
Out[15]: 
   A  B
0  1  2
1  1  4
2  5  6

In [16]: g1.apply(lambda x: x) 
Out[16]: 
   A  B
0  1  2
1  1  4
2  5  6

In [18]: g.agg(lambda x: x.sum())
Out[18]: 
   B
A   
1  6
5  6

In [19]: g1.agg(lambda x: x.sum())  # Note: A is not summed
Out[19]: 
   A  B
0  1  6
1  5  6
```

My opinion is that head/tail/nth should act like filter (i.e. both ignore the as_index).

**Comment by jseabold** [comment]
Parking this here, because I think (?) it's the same issue.

```
In [20]: paste
df = pd.DataFrame()
y = np.random.randint(2, size=25)
labels = np.repeat(['a', 'b', 'c', 'd', 'e'], 5)
df['dv'] = y
df['label'] = labels
gb = df.groupby(['label','dv'], as_index=False).size()

## -- End pasted text --

In [21]: gb
Out[21]:
label  dv
a      0     3
       1     2
b      0     3
       1     2
c      1     5
d      0     3
       1     2
e      0     2
       1     3
dtype: int64
```

**Comment by hayd** [comment]
@jseabold Is that: `size` doesn't respect `as_index` ?

**Comment by jseabold** [comment]
Yeah.

**Comment by jreback** [comment]
@jorisvandenbossche should update this, and include #13519

**Comment by jorisvandenbossche** [comment]
@jreback Yes, this is one of the topics I planned to tackle

**Comment by dsaxton** [comment]
I wrote out a separate issue for `size` (using `pandas` 0.25) and then found that this has been open for a while.  My expectation would be that this would create a separate column (especially given that one of the common uses of `as_index=False` is to facilitate subsequent joins), perhaps with the counts simply being labeled `"size"`.  Could it make sense to follow this naming pattern with some of the other aggregations as well (e.g., generic `apply`) to be consistent with column-naming in SQL (the documentation does say that the output is "SQL-style")?

**Comment by rhshadrach** [comment]
Currently nunique with as_index=False reports the number of unique elements for the grouping column, which is tautologically 1:

````
df = DataFrame({"A": list("abbacc"), "B": list("abxacc"), "C": list("abbacx")})
df.groupby("A", as_index=False).nunique()
````

df:

````
   A  B  C
0  a  a  a
1  b  b  b
2  b  x  b
3  a  a  a
4  c  c  c
5  c  c  x
````

result:

````
   A  B  C
0  1  1  1
1  1  2  1
2  1  1  2
````

It seems to me it'd be better to leave the grouping column as-is:

````
   A  B  C
0  a  1  1
1  b  2  1
2  c  1  2
````

Is there a reason the current behavior is a feature that we don't want to change?

**Comment by rhshadrach** [comment]
As far as I can tell, all issues with consistencies for reduction kernels with `as_index=False` have been solved. I think this issue can be closed.
