### ISSUE TITLE
ENH: Add Rich formatting support to Pandas object displays with `__rich_console__` method

### ISSUE THREAD

**Issue by dwreeves** [pandas-dev/pandas#57572]
### Feature Type

- [x] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

[Rich](https://github.com/Textualize/rich) is a very popular and, at this point, a standard tool in the Python ecosystem for beautiful rendering of text in terminals. Pandas's rich rendering via `_repr_html_` is very optimized for the Jupyter ecoystem, but lags behind in the terminal space. As someone who primarily codes in a terminal with a Rich patched REPL, I find this unfortunate and unnecessary. Hence I am adding this feature request in hopes that the situation can be improved. I can work on this if it is agreed that this feature would be handy and useful.

### Feature Description

This is a very rough solution that does not cover all the appropriate challenges, requirements and complexities that would need to be met. It is just to give you an idea that it is possible:

```python
import pandas as pd

class DataFrame(pd.DataFrame):

    def __rich_console__(self, console: "rich.console.Console", console_options: "rich.console.Console"):
        from rich.table import Table
        table = Table()
        table.add_column(self.index.name if self.index.name is not None else "")
        for c in self.columns:
            table.add_column(str(c))
        for r in self.itertuples():
            table.add_row(*map(str, r))
        yield from table.__rich_console__(console, console_options)

from rich.console import Console

console = Console()

df = DataFrame([
    {"name": "John Doe", "phone": "555-555-5555", "last_purchase_amount": 1.23},
    {"name": "Mary Sue", "phone": "800-123-4567", "last_purchase_amount": 100.00}
])

console.print(df)
```

A few things are missing from this solution. Notably, it needs to hook into the Pandas options; it needs to be able to truncate the rows and columns based on the relevant display options. Series objects also need to have a `__rich_console__`. The Styler object should, as well, and this should hook into the Styler object configuration. There should probably be a way to set additional display options for this somewhere (e.g. `display.rich.[...]` and `styler.rich.[...]`). You'd need to hook into the try-except import stuff that Pandas does on the backend for optional dependencies. Lastly, of course, this would all need to be documented.

### Alternative Solutions

- Users can just do it themselves, I suppose.
- You can use the `__rich__` method, but I think you'd want to have access to the console parameters when fleshing out the code.

### Additional Context

I could not find any related issues.

**Comment by Delengowski** [comment]
Can you show examples?

Specifically with and without a `pandas.MultiIndex` both axis 1 and axis 2? Without and without axis 0 names? What kind of support does `rich` provide for multi indexes?

**Comment by mroeschke** [comment]
Looks like there's this external library that supports rich for pandas objects: https://pypi.org/project/rich-dataframe/

**Comment by dwreeves** [comment]
@Delengowski 

> Can you show examples?

The example code I provided in the issue outputs like this:

![image](https://github.com/pandas-dev/pandas/assets/31971762/4986f07a-d94b-4353-bd0d-03656e282d25)

One can certainly do additional work however to implement more styling options. Rich has a bunch.

> Specifically with and without a `pandas.MultiIndex` both axis 0 and axis 1? Without and without axis 0 names? What kind of support does `rich` provide for multi indexes?

Multiindexes are a good point. Rich does not "provide support for multindexes" per se, it's is just a visualization library. The way you render them depends on how you want to render them.

With my code example above the following dataframe:

```python
df = DataFrame(
    [
        {"name": "John Doe", "phone": "555-555-5555", "last_purchase_amount": 1.23},
        {"name": "Mary Sue", "phone": "800-123-4567", "last_purchase_amount": 100.00},
    ],
    index=pd.MultiIndex.from_tuples([(1, 2), (3, 4)], names=[None, None])
)
```

You get this:

![image](https://github.com/pandas-dev/pandas/assets/31971762/f6b057ba-a1ae-4b1e-b320-23a8507c0b7e)

You can modify the code to support more functionality, though:

```python
import pandas as pd

# todo: replace with actual pandas settings
settings__display_rich_combine_multindex = False

class DataFrame(pd.DataFrame):

    def __rich_console__(self, console: "rich.console.Console", console_options: "rich.console.Console"):
        from rich.table import Table
        table = Table()
        split_multiindices = False
        # Todo: check if there is a better way to check for multi indices
        if self.index.names and not settings__display_rich_combine_multindex:
            split_multiindices = True
            for name in self.index.names:
                table.add_column(name if name is not None else "")
        else:
            if self.index.names:
                name = ",".join(self.index.names)
            else:
                name = self.index.name
            table.add_column(name if name is not None else "")

        for c in self.columns:
            table.add_column(str(c))
        for r in self.itertuples():
            if split_multiindices:
                row_data = map(str, [*r[0], *r[1:]])
            else:
                row_data = map(str, r)
            table.add_row(*row_data)

        yield from table.__rich_console__(console, console_options)

from rich.console import Console

console = Console(color_system="truecolor")

df = DataFrame(
    [
        {"name": "John Doe", "phone": "555-555-5555", "last_purchase_amount": 1.23},
        {"name": "Mary Sue", "phone": "800-123-4567", "last_purchase_amount": 100.00},
    ],
    index=pd.MultiIndex.from_tuples([(1, 2), (3, 4)], names=["foo", "bar"])
)

console.print(df)
```

Output:

![image](https://github.com/pandas-dev/pandas/assets/31971762/f121dc74-08bf-4394-af03-afb296ebd300)

You can do the thing where you create a new row just for the index names, if you want, as well. Again, it's very composable.

**Comment by dwreeves** [comment]
@mroeschke

> Looks like there's this external library that supports rich for pandas objects: https://pypi.org/project/rich-dataframe/

I'm aware, and the owners of that library should definitely be consulted and should be brought into this discussion if we agree that this should exist as a native efeature, as they have relevant knowledge and I'm sure they'd love to see this become a native feature.

But, I do think there is a lot of value in making this native, and not just relying on third-party support.

I would put it like this: if there was a library called `jupyter-dataframe`, it would still have been a good idea for Pandas to implement `_repr_html_` natively. It would not be a good user experience to tell people, "well, just use this third party library and wrap everything with `jupyter_dataframe.prettify(df)`.

Some of the benefits of adding this natively:

- Just type `>>> df` and get your pretty repr, instead of needing to wrap in `prettify(df)`. That's a massive difference in quality of life for exploratory workflows.
- User does not need to install another library.
- Likely to receive more functionality, bugfixes, and community support. For example, the linked library does not seem to support MultiIndexes, which I was just asked about above.
- People are way more likely to use this in general, I think, if it is officially supported.

Again, Rich is popular (46k Github stars), modern, and people just really enjoy it. I'm not proposing pandas-dev creates a new optional dependency on some random no-name library. I'm proposing that terminal-based Pandas workflows should get a modern, native, built-in facelift.

**Comment by dwreeves** [comment]
It looks like all the unit-tests for Pandas normal reprs are:

- For dataframes: https://github.com/pandas-dev/pandas/blob/main/pandas/tests/frame/test_repr.py
- For series + other things: https://github.com/pandas-dev/pandas/blob/main/pandas/tests/series/test_formats.py

Obviously, reasonable acceptance criteria would be that a Rich hook can implement all of these behaviors but as Rich-formatted tables. (There are a few stylistic decisions that one would still have to make even within this constraint, however, but reimplementing the spirit of these tests but for Rich would really narrow down the scope of the problem.)

**Comment by Delengowski** [comment]
> Note that all of this code is very rough. Implementing this would take a lot, lot more effort than I put into this code right here. I'm just trying to see first whether the Pandas dev team agrees that this should be implemented.

Thanks for this. The first thought that came to mind was merging of cells for multi index. I would think that unless Rich can do that, it's a non starter because displaying rich bases repr for a data frame with multi index that looks different from the regular repr would be incredibly confusing. 


That's why I was asking, to see if it has out of box support or if it would be a bit of work.

**Comment by Delengowski** [comment]
It looks like spans are desired but not yet implemented nor a high priority.

https://github.com/Textualize/rich/issues/164

**Comment by dwreeves** [comment]
I think showing MultiIndexes as a single column and `str.ljust()`ing so things line up would be fine. I don't think displaying MultiIndexes should necessarily require a span unless I'm missing something.

**Comment by dwreeves** [comment]
Here is an example of the snippet code modified to emulate the rowspan-like visualization that the base repr provides:

```python
import pandas as pd

# todo: replace with actual pandas settings
settings__display_rich_combine_multindex = False

class DataFrame(pd.DataFrame):

    def __rich_console__(self, console: "rich.console.Console", console_options: "rich.console.Console"):
        from rich.table import Table
        table = Table()
        split_multiindices = False
        # Todo: check if there is a better way to check for multi indices
        if self.index.names and not settings__display_rich_combine_multindex:
            split_multiindices = True
            for name in self.index.names:
                table.add_column(name if name is not None else "")
        else:
            if self.index.names:
                name = ",".join(self.index.names)
            else:
                name = self.index.name
            table.add_column(name if name is not None else "")

        _prev_index = None

        for c in self.columns:
            table.add_column(str(c))
        for r in self.itertuples():
            if split_multiindices:
                if _prev_index is not None:
                    new_index = [
                        new if prev != new else ""
                        for prev, new in zip(_prev_index, r[0])
                    ]
                else:
                    new_index = r[0]
                _prev_index = r[0]
                row_data = map(str, [*new_index, *r[1:]])
            else:
                row_data = map(str, r)
            table.add_row(*row_data)

        yield from table.__rich_console__(console, console_options)

from rich.console import Console

console = Console(color_system="truecolor")

df = DataFrame(
    [
        {"name": "John Doe", "phone": "555-555-5555", "last_purchase_amount": 1.23},
        {"name": "Mary Sue", "phone": "800-123-4567", "last_purchase_amount": 100.00},
        {"name": "Bob James", "phone": "800-234-5678", "last_purchase_amount": 50.00},
    ],
    index=pd.MultiIndex.from_tuples([(1, 1), (1, 2), (2, 1)], names=["foo", "bar"])
)

console.print(df)
```

This is the output:

![image](https://github.com/pandas-dev/pandas/assets/31971762/e7fc0ac2-832b-4970-a337-403d82fc2c3e)

However, you can see that it looks bad when I replace `table = Table()` with `table = Table(show_lines=True)`:

![image](https://github.com/pandas-dev/pandas/assets/31971762/ab659c3e-8260-491e-b3bc-da1a69fd2459)

The 'work around' I propose is, when `show_lines=True`, we display everything:

![image](https://github.com/pandas-dev/pandas/assets/31971762/9a2095bc-ae11-4081-b4f1-137bb31946f5)

In the sloppy draft code above, you can achieve this by replacing this line: `if _prev_index is not None:` with: `if _prev_index is not None and not table.show_lines:`

**Comment by kushikks** [comment]
take
