### ISSUE TITLE
DOC: easing building of the docs for contributors

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#5934]
Contributing to the docs (and so building the docs) should be as easy as possible to promote this, which is not always the case (eg see comment here https://github.com/pydata/pandas/pull/5530#issuecomment-32138220). Thanks to @y-p to pushing some things forward yesterday, and I thought of making an overview of all issues related to this:
- [x] Building of the docs fails with current stable sphinx 1.2 (#5899).  
  - It does work with 1.1.3 and with development version of sphinx (bug already fixed). In #5921 there was a discussion on this (removing template class.rst would temporarily solve this, but some of the generated docstring pages would be lost). For the moment this is left as is. At least, there should be a clear warning for this.  
    Does somebody see another solution?
- [x] On Windows, doc building fails on some unicode error in io.rst (#5142).  
  - See also #5245 and #5926.
  - Fixed by #5925.
- [ ] On Windows, the removal of temporary files cause errors (#5933). 
- [x] Building of the docs is not python 3 compatible at the moment (#5479, #5530)
  - This should be solved after updating to ipython's version (#5221, #5925)
- [x] There should be a better guide to building the documentation.  
  - To be fixed by #5996.

Any others?

**Comment by mroeschke** [comment]
Building the documentation is well documented, and since there's only one issue left, will close this issue and let that issue stand. Closing.
