### ISSUE TITLE
INT: mixin for PeriodIndex / Datetimeindex for common methods

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#6469]
related #6779
- [x] `asobject` (#7544)
- [x] `__unicode__` (#7602)
- [x] `min/max` (#7609)
- [x] `summary` (#9116)
- [x] `equals` (#13986)
- [x] `isin`
- [x] `unique` (#7540, #7843) 
- [x] `value_counts` (#7735)
- [x] `resolution` (#7708)
- [x] `__iter__` (#7702, #7709, #7720)
- [x] `__add__`, `__iadd__`, `__sub__`, `__isub__` (#7741) 
- [x] `__getitem__` (#10292, for `DatetimeIndex` and `TimedeltaIndex`) (#13987, for `PeriodIndex`)
- [x] `repeat` (#13995)
- [x] `NaT` related methods / property. `hasnans`, `_isnan`, `_na_value` (#13997)

next priorities:
- [x] `get_duplicates`
- [x] `repeat`
- [ ] `get_value` / `get_value_maybe_box`
- [ ] `searchsorted`
- [x] `argmin` / `argmax`

**Comment by sinhrks** [comment]
Sorry about leaving it a while, updated the list including #10292. ``get_value`` and ``searchsorted`` seems to be on separate classes. Will check whether can be integrated...

**Comment by jbrockmendel** [comment]
Equals and isin can be checked off

**Comment by jbrockmendel** [comment]
I think this has been pushed about as far as it can go, can be closed.

**Comment by jbrockmendel** [comment]
This has been pushed as far as it can go, closing.
