### ISSUE TITLE
ENH: SQL Enhancement for the Future

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#6701]
0.14 Enhancements : #6292
- [x] handle no rows returns from a sql query, #3745 
- [ ] option for default_charset to sql.write_frame #5008 
- [x] sql to provided NaN/NaT conversions #2754 -> PR #8208
- [x] specify chunksize for sql.read_frame #2908 -> PR #8330 
- [ ] SQL through SQLAlchemy - check performance #6416
- [ ] mangle_dup_columns for read_frame (#2738)

**Comment by kokes** [comment]
All but the second issue have been resolved. And that issue is regarding a long removed API, that has since been replaced by a SQLAlchemy-backed API, so we'll see, maybe it's no longer an issue (see followup in #5008).

**Comment by mroeschke** [comment]
All the issues in the post have been addressed. I think we can close this tracker for more specific issues.
