### ISSUE TITLE
Split/Partition Master Issue

### ISSUE THREAD

**Issue by cpcloud** [pandas-dev/pandas#7387]
As pointed out by @dsm054, there are multiple lurking split/partition API requests. Here are the issues and a short summary of what they would do (there are some duplicates here, I've checked off those issues/PRs that have been closed in favor of a related issue):
- [x] #414: (i think) original issue for these ideas going back 3 years
- [x] #936: windowing with time-length windows like `pd.rolling_mean(ts, window='30min')` and possibly even arbitrary windows using another column
- [x] #3066: `split` method on pandas objects, playing around with ideas
- [x] #3101: a closed PR by @y-p to use the args of lambda to group a frame into views of a sliding window
- [x] #3685: resampling using the first `n` samples of a bin.
- [ ] #4059: `np.array_split` style API where you can split a pandas object into a list of `k` groups of possibly unequal size (could be a thin wrapper around `np.array_split`, or more integrated into the pandas DSL). IMO, this issue provides the best starting point for an API. [SO usage](http://stackoverflow.com/questions/24461906/how-can-i-divide-up-a-pandas-dataframe/24462529#24462529)
- [x] #5494: an API for to allow pandas' `groupby` to have `itertools.groupby` semantics (i.e., preserve the order of duplicated group keys), i.e., `'aabbaa'` would yield groups `['aa', 'bb', 'aa']` rather than `['aaaa', 'bb']`. There'd have to be some changes to the use of `dict` in the groupby backend as noted by @y-p here https://github.com/pydata/pandas/issues/4059#issuecomment-29061036.
- [ ] #6675: Ability to select ranged groups via another column, like "select all rows between the values X and Y from column C", e.g., an "events" column where you have a start and end markers and you want to get the data in between the markers. There are a couple of ways you can do this, but it would be nice to have an API for this. This is very similar to #936.

The [`toolz`](https://github.com/pytoolz/toolz) library has a `partitionby` function that provides a nice way to do some of the splitting on sequences and might provide us with some insight on how to approach the API.

cc @jreback @jorisvandenbossche @hayd @danielballan

**Comment by mroeschke** [comment]
Since there's only 2 issues here, I think it's okay to track those issue separately as this tracker isnt really used anymore. Closing
