### ISSUE TITLE
Allowing the index to be referenced by name, like a column

### ISSUE THREAD

**Issue by makmanalp** [pandas-dev/pandas#8162]
- [ ] #13243 use df.index/df.columns names to automatically choose axis along which to broadcast
- [ ] #11373 Request for some kind of named arguments loc
- [ ] #4036 Partial Selection on MultiIndex: The need for empty slice support & dict indexing

What if we allowed the index of a dataframe to be referred to in the usual ways?

``` python

data = pd.read_table("...", index_col="id")
data.id  # breaks
data["id"]  # breaks
```

I find myself setting and resetting indices very often to join to a different dataframe or to pull in the values of the index to a subselection of the dataframe, etc. I figure this is because of how the data is stored under the hood, but wouldn't this be convenient?

**Comment by TomAugspurger** [comment]
Just to reraise this with another use-case, this would help out matplotlib with their [labeled data](https://github.com/matplotlib/matplotlib/pull/4829) plotting. I haven't looked recently, but an earlier version had to workaround not being able to use `__getitem__` to get to the index.

I'm less sure about the need to allow `df[['index_name', 'other_col']]`.

**Comment by makmanalp** [comment]
@TomAugspurger in defense of `df[['index_name', 'other_col']]`, what's nice about it is that it saves you from a ton of gross `foo.reset_index().blah.set_index()` and other similar cruft that isn't really meaningful and obscures what your code is actually trying to do.

**Comment by tacaswell** [comment]
There is currently code on that branch so that

```python
plt.plot('foo', data=df)
plt.plot(df['foo'])
``

Will grab both the index to use as the index instead of `range`, but that is _only_ implemented for `plot`, but nothing else.

**Comment by JanSchulz** [comment]
This "problem" was also on the ggplot todo list. I would vote for `__index__` beeing treated special (=return df.index) and have named index also show up in `df[<...>]`

**Comment by jbrockmendel** [comment]
Transplanting from #17061 on convergence in Index/Series behavior.

It would be nice to be able to access `foo.dt` without first having to check whether `foo` is an `Index` or `Series`.  This could be accomplished by having `DatetimeIndex`, `PeriodIndex`, and `TimedeltaIndex` have a property `dt` that just returns `self`.  If others agree, I'll put together a PR.  Thoughts?

**Comment by MarcoGorelli** [comment]
If I've understood the suggestion correctly, I'm -1 on it, because of the ambiguity in what should happen if a column has the same name as the index
```python
In [5]: df
Out[5]:
   a  b
a
7  1  4
8  2  5
9  3  6

# what does df['a'] return?
```

**Comment by MarcoGorelli** [comment]
closing as per today's discussion then - thanks anyway for the issue

**Comment by tacaswell** [comment]
@MarcoGorelli Is there a link to any notes from the discussions?

**Comment by MarcoGorelli** [comment]
yes but they just say "agreed to close" 😄 

A related issue which was brought up is https://github.com/pandas-dev/pandas/issues/27652, which may still be considered

**Comment by tacaswell** [comment]
😞 

I am curious what the persuasive argument was.

I see how from inside of pandas the index is very special, but from the outside it just looks like any other column.  In the case where you need to consume input from users of many types (which may just be a Matplotlib problem) being able to treat dict-of-array, dataframes, h5py groups, xarray, [anything that returns an array for `__getitem__(key: str) -> Array`], etc is pretty nice.  From the outside it is a weird wart that there is data on dataframes that can not be extract via `__getitem__`.

On the other hand I see the namespace problem may be intractable and the above use case might be niche enough that it is not worth the engineering and documentation effort to make it work.

**Comment by jbrockmendel** [comment]
The main pain point was cases where there the index name(s) matched a column label

**Comment by MarcoGorelli** [comment]
Personally, I'd rather not add even more auto-magic and inconsistencies. This is going to open up more issues. There's enough to work on. If a [PDEP ](https://github.com/pandas-dev/pandas/pull/53576) were raised, I'd probably vote down, sorry

But that doesn't mean you need to give up hope 😄  If you can get another core member on board, write a PDEP with them, and then get a 2/3 majority of core members to vote it up, then you could bypass my negativity
