### ISSUE TITLE
DEPR/DOC: rpy deprecation

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#9602]
so we should put up a deprecation notice on `rpy`imports that in the future the user should use  `rpy2` directly rather than the less-supported  `pandas.rpy` converters that we can take action say in 0.17.0

discussed extensivley in #7385 

xref #7385, #9187 #7309, #8255 
- [x] Update the docs with some example of how to port your pandas examples to the `rpy2` API -> done with #10075
- [ ] Go over the functionality in pandas and check if some things should be ported to `rpy2` (what still works better in pandas?)
  - [ ] Handling of NaN values (comment below: https://github.com/pydata/pandas/issues/9602#issuecomment-94716332)
  - [ ] index is not preserved in `ri2py` -> this should be handled in https://bitbucket.org/rpy2/rpy2/issues/285
- [ ] The closed PRs -> push them to `rpy2`?

**Comment by jorisvandenbossche** [comment]
I put some todo's above.

**Comment by sebp** [comment]
Regarding the second item in the list, rpy2 currently does not handle missing values correctly, a NaN value will remain NaN in R and not be considered a missing value (NA). The function pandas.rpy.common.convert_to_r_dataframe performed the conversion correctly.

**Comment by jorisvandenbossche** [comment]
@jreback I moved this to 0.16.1 milestone: I think we should at least have a link the deprecation warning to the docs, where a minimal link is how to port your code. This minimal thing should not be much work, and I will do it this week.

**Comment by jreback** [comment]
@jorisvandenbossche awesome! thks.

**Comment by datnamer** [comment]
Can we wait for Rpy2 to handle the conversion correctly before deprecating this?

**Comment by jorisvandenbossche** [comment]
@lgautier @davclark Need some help here.

What is currently the recommended way to do conversion between rpy2 objects and pandas objects? 
As your answer on SO (http://stackoverflow.com/questions/20630121/pandas-how-to-convert-r-dataframe-back-to-pandas) does not seem to be correct anymore? `pandas2ri.pandas2ri` and `pandas2ri.ri2pandas` don't exist anymore?

I put some things in a notebook: http://nbviewer.ipython.org/gist/jorisvandenbossche/d0deaa53ace697e1514e 
What I basically did is:

* doing these imports: 

  ```
import rpy2.robjects.conversion as conversion
from rpy2.robjects import pandas2ri
pandas2ri.activate()
```

*  after that, to do explicit conversions, use following functions to replace the pandas ones:
  * `com.convert_to_r_dataframe(df)` -> `conversion.py2ri(df)`
  * `com.convert_robj(rdf)` -> `conversion.ri2py(rdf)`

  There are also like `pandas2ri.ri2py_dataframe` and `pandas2ri.py2ri_pandasdataframe`, but I assume these are only for the dispatch and not meant to use directly?

Does the above look OK to put in our docs? Or are there better ways? 
The above works, apart from some difference between the conversion currently in pandas and rpy2 (eg NaN values not converted in rpy2), but those should be ported from pandas to rpy2

**Comment by jorisvandenbossche** [comment]
@datnamer You have some point that deprecating was a bit early, but you can be assured that we won't remove for some release and until that is sorted out.

**Comment by davclark** [comment]
I would not use activate outside of user code, as it monkey-patches the
conversion machinery. You should be able to use the ri2pandas versions
directly.

**Comment by lgautier** [comment]
@jorisvandenbossche : the conversion system has changed and is now using single dispatch. Use the registration to add a conversion.

The doc is here: http://rpy.sourceforge.net/rpy2/doc-2.5/html/robjects_convert.html#conversion-functions

**Comment by jorisvandenbossche** [comment]
@davclark @lgautier Thanks for your input!

- What I wrote above would be to put in our docs as recommendations for *users* of pandas to do, so in that case it is OK to advice the use of `activate`? 
  Using `pandas2ri.py2ri_pandasdataframe` doesn't look that nice (but I can certainly mention these as the specific conversion functions).
- @lgautier I don't think we need to use the conversion system, as the pandas <-> ri conversion functions are included in rpy2. So I was just looking for where to point our users to for porting there pandas code to rpy2 (of course, if we could keep the conversions in pandas, using the dispatch system would indeed be the way to go instead of the custom `pandas.rpy2.common.convert_to_r_dataframe(df)` functions. But for now we decided to remove it in pandas and improve the existing conversion functions in rpy2)

**Comment by davclark** [comment]
Oh - I misunderstood! It is absolutely appropriate to recommend users to user activate().

**Comment by jorisvandenbossche** [comment]
We put a deprecation warning on the `pandas.rpy` module, but we did not have docs yet that explained what users can use in place of our conversion functions, so I needed the up to date way to do it in rpy2

**Comment by jorisvandenbossche** [comment]
I put up a small porting guide, see #10075

**Comment by ajmazurie** [comment]
This has been mentioned above already, but the new recommended conversion method `rpy2.robjects.conversion.py2ri` (and `rpy2.robjects.pandas2ri.py2ri_pandasdataframe`) doesn't handle NaN correctly. This is a significant problem for which I haven't been able to find a solution yet. Is there a way to fix this?

**Comment by davclark** [comment]
Thanks for highlighting this Aurélien. Is there an issue on the rpy2 issue
tracker for this?

**Comment by datnamer** [comment]
+1

**Comment by ajmazurie** [comment]
Not that I know of; or my Google-fu failed me.
Aurelien

**Comment by jorisvandenbossche** [comment]
I opened an issue at rpy2 to track this there as well: https://bitbucket.org/rpy2/rpy2/issue/282/missing-features-in-rpy2s-pandas2ri

The solution is to improve `rpy2`'s conversion functions (in fixing them, or porting some of the pandas code to rpy2 if possible), and contributions for this would be very welcome! (but rest assured, the functions in pandas, although deprecated, will not be effectively removed until these issues are solved)

**Comment by lgautier** [comment]
@jorisvandenbossche The issue in the link (issue 282 on rpy2's issue tracker on bitbucket) has been closed. `rpy2` conversion feature set for pandas data frames is arguably ahead ;-).

**Comment by datnamer** [comment]
@lgautier  Great! thanks for all your hard work on this and other Rpy2 stuff :)

**Comment by jreback** [comment]
@jorisvandenbossche did we remove this?

**Comment by jorisvandenbossche** [comment]
No, we did not yet remove this, because there are (or were, should be checked) still some issues with the rpy2 alternative that were better supported in the pandas version. Needs someone to go over this (but ideally someone who uses `pandas.rpy` / `rpy2`).

**Comment by lgautier** [comment]
@jorisvandenbossche Unless the issues are reported in the `rpy2` tracker there is a good chance noone will work on them:  https://bitbucket.org/rpy2/rpy2/issues?status=new&status=open . If you add a link to an entry in the `pandas` tracker I can comment back when the issue status is changing (we worked that way for the `rmagic` before it was moved to `rpy2`).

**Comment by wesm** [comment]
It's my preference to deprecate `pandas.rpy` and remove in pandas 1.0. I think this can be handled by a 3rd-party package

**Comment by jorisvandenbossche** [comment]
@wesm It's already deprecated for a couple of releases, and we indeed should certainly remove it. At the time of deprecation, there were still some issues in ``rpy2`` (things that were handled better in the `pandas.rpy` code), but as @lgautier notes above, those should be solved nowadays. 
I just want to go through those reported issues and check that they are indeed solved / update our migration docs, and then we can remove the module in the next release.

**Comment by jorisvandenbossche** [comment]
Was looking into this today, but ran into some issues converting simple dataframes, reported here: https://bitbucket.org/rpy2/rpy2/issues/394/pandas2ripy2ri-on-basic-dataframe-falls

But in any case, will put up a PR to remove the module.

**Comment by davclark** [comment]
Being gnomish - the above issue has resolved to a documentation issue.
