### ISSUE TITLE
BUG: losing Index/Series names master issue

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#9862]
cases where index names are lost in various operations, most of these involve an issue in `concat`
## Index.name
- [ ] `Panel.fillna`, #3570
- [ ] groupby on empty, #8093
- [x] `.append`, https://github.com/pydata/pandas/issues/9857 (closed by #9876)
- [x] groupby `.size`, #9925 
- [x] timedelta ops, #9926 
- [ ] `.intersection/.union`, #9943
- [x] `drop_duplicates`, #10116
- [x] `to_datetime/to_timedelta` #10875 (closed by #10945)
- [ ] `Index.__new__` #11193
## Series.name
- [x] rolling_\* funcions #10659
- [x] dt accessor funcions #10712
- [x] quantile #10881

**Comment by ksanghai** [comment]
I am working on this issue now.. lets see how far I can get..

**Comment by jreback** [comment]
```
In [1]: Index(['a'],name='foo').append(Index(['b']))
Out[1]: Index([u'a', u'b'], dtype='object')

In [2]: Index(['a'],name='foo').append(Index(['b'])).name
```

**Comment by sinhrks** [comment]
How about making ``testing.assert_index_equal`` to check name attribute (maybe optionally) to detect this kind of problems?

**Comment by jorisvandenbossche** [comment]
+1 `testing.assert_frame_equal` does this already, so it seems logical that `assert_index_equal` can do this as well (and then we can also clean up `assert_frame_equal` a bit)

**Comment by jreback** [comment]
IIRC the checking names option was turned off as a default quite a while ago, because too many things were breaking; I suspect it would be much closer nowadays. so +1 here as well.

**Comment by sinhrks** [comment]
Added #9925 and #9926 to the list, which found by changing ``assert_index_equal`` to check index names.

**Comment by sergeny** [comment]
https://github.com/pydata/pandas/issues/9943

**Comment by Licht-T** [comment]
@jreback #8093 seems already fixed.
https://github.com/pandas-dev/pandas/issues/8093#issuecomment-339043936

**Comment by Dr-Irv** [comment]
@jreback #11193 is closed by #11193
